feat: menambah colom terbaca
Saonoke/RWGram pull request #25
Opened 2024-04-27 14:12 UTC by ridlofebrio

2024-04-27 14:16 UTC, Saonoke requested changes

2024-04-27 14:16 UTC, Saonoke commented on database/migrations/2024_04_02_075505_bansos_table.php
bansos gausah feb, UMKM sing perlu

2024-04-27 14:21 UTC, ridlofebrio commented on database/migrations/2024_04_02_075505_bansos_table.php
eh salah inputno a aku

2024-04-27 14:23 UTC, ridlofebrio commented on database/migrations/2024_04_02_075505_bansos_table.php
iso dihapus kan yo??

2024-04-28 03:15 UTC, Saonoke commented on database/migrations/2024_04_02_075505_bansos_table.php
commit sing podo karo commit an iki

2024-04-28 11:22 UTC, Saonoke approved these changes

2024-04-28 11:22 UTC, merged